// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqzberyhuypxrumeafcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xemJlcnlodXlweHJ1bWVhZmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODYzNzcsImV4cCI6MjA2MDY2MjM3N30.ozIAKpNMWEebQSIBZzwiruEIHiNm_buxgm8rV24v82U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);